"""baseline

Revision ID: 33ed48b78942
Revises: 
Create Date: 2026-02-12 22:01:51.328063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33ed48b78942'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("availability_status IS NULL OR availability_status IN ('AVAILABLE','LIMITED','BUSY')", name='ck_users_availability_status'),
    sa.CheckConstraint("role IS NULL OR role IN ('FILMMAKER','COMPOSER','BOTH')", name='ck_users_role'),
    sa.CheckConstraint("username ~ '^[a-z0-9._]{3,30}$'", name='ck_users_username_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('composer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('primary_focus', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('instruments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("primary_focus IS NULL OR primary_focus IN ('INSTRUMENTAL','ELECTRONIC','HYBRID')", name='ck_composer_profiles_primary_focus'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('filmmaker_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('disciplines', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('sub_category', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.Column('active_media_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('NARRATIVE_FILM','EXPERIMENTAL','ACTION_SPORTS','MOTION_GRAPHICS','REELS')", name='ck_projects_category'),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','COMPLETED')", name='ck_projects_status'),
    sa.CheckConstraint("visibility IN ('PRIVATE','UNLISTED','PUBLIC')", name='ck_projects_visibility'),
    sa.ForeignKeyConstraint(['active_media_version_id'], ['media_versions.id'], name='fk_projects_active_media_version_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('OWNER','CONTRIBUTOR')", name='ck_project_members_role'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_seconds', sa.Integer(), nullable=True),
    sa.Column('end_seconds', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_seconds IS NULL OR end_seconds >= 0', name='ck_segments_end_seconds'),
    sa.CheckConstraint('start_seconds IS NULL OR end_seconds IS NULL OR end_seconds >= start_seconds', name='ck_segments_time_range'),
    sa.CheckConstraint('start_seconds IS NULL OR start_seconds >= 0', name='ck_segments_start_seconds'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_project_id'), 'segments', ['project_id'], unique=False)
    op.create_table('media_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_mime', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("media_type IN ('VIDEO','AUDIO')", name='ck_media_versions_media_type'),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='ck_media_versions_duration_seconds'),
    sa.CheckConstraint('version_number >= 1', name='ck_media_versions_version_number'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'segment_id', 'media_type', 'version_number', name='uq_media_versions_version')
    )
    op.create_index(op.f('ix_media_versions_project_id'), 'media_versions', ['project_id'], unique=False)
    op.create_index('ix_media_versions_project_segment', 'media_versions', ['project_id', 'segment_id'], unique=False)
    op.create_index('ix_media_versions_project_type', 'media_versions', ['project_id', 'media_type'], unique=False)
    op.create_index(op.f('ix_media_versions_segment_id'), 'media_versions', ['segment_id'], unique=False)
    op.create_index(op.f('ix_media_versions_uploaded_by'), 'media_versions', ['uploaded_by'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('media_version_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timecode_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('timecode_seconds IS NULL OR timecode_seconds >= 0', name='ck_comments_timecode_seconds'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_version_id'], ['media_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_media_version_id'), 'comments', ['media_version_id'], unique=False)
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    op.create_index(op.f('ix_comments_segment_id'), 'comments', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_segment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_media_version_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_media_versions_uploaded_by'), table_name='media_versions')
    op.drop_index(op.f('ix_media_versions_segment_id'), table_name='media_versions')
    op.drop_index('ix_media_versions_project_type', table_name='media_versions')
    op.drop_index('ix_media_versions_project_segment', table_name='media_versions')
    op.drop_index(op.f('ix_media_versions_project_id'), table_name='media_versions')
    op.drop_table('media_versions')
    op.drop_index(op.f('ix_segments_project_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('filmmaker_profiles')
    op.drop_table('composer_profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
