"""add project member status

Revision ID: 80dbd787a8d8
Revises: 33ed48b78942
Create Date: 2026-02-17 15:25:04.085556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80dbd787a8d8'
down_revision: Union[str, Sequence[str], None] = '33ed48b78942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('status', sa.Text(), nullable=False))
    op.create_foreign_key('fk_projects_active_media_version_id', 'projects', 'media_versions', ['active_media_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_active_media_version_id', 'projects', type_='foreignkey')
    op.drop_column('project_members', 'status')
    # ### end Alembic commands ###
