"""add music cues and cue_id

Revision ID: 82c668a047db
Revises: e5e44a545816
Create Date: 2026-02-18 20:51:23.217345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c668a047db'
down_revision: Union[str, Sequence[str], None] = 'e5e44a545816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_cues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('video_version_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('start_seconds', sa.Integer(), nullable=False),
    sa.Column('end_seconds', sa.Integer(), nullable=False),
    sa.Column('active_audio_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_seconds >= 0', name='ck_music_cues_end_seconds'),
    sa.CheckConstraint('end_seconds >= start_seconds', name='ck_music_cues_time_range'),
    sa.CheckConstraint('start_seconds >= 0', name='ck_music_cues_start_seconds'),
    sa.ForeignKeyConstraint(['active_audio_version_id'], ['media_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_version_id'], ['media_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_cues_active_audio_version_id'), 'music_cues', ['active_audio_version_id'], unique=False)
    op.create_index(op.f('ix_music_cues_project_id'), 'music_cues', ['project_id'], unique=False)
    op.create_index(op.f('ix_music_cues_video_version_id'), 'music_cues', ['video_version_id'], unique=False)
    op.add_column('media_versions', sa.Column('cue_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_media_versions_cue_id'), 'media_versions', ['cue_id'], unique=False)
    op.create_foreign_key(None, 'media_versions', 'music_cues', ['cue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_versions', type_='foreignkey')
    op.drop_index(op.f('ix_media_versions_cue_id'), table_name='media_versions')
    op.drop_column('media_versions', 'cue_id')
    op.drop_index(op.f('ix_music_cues_video_version_id'), table_name='music_cues')
    op.drop_index(op.f('ix_music_cues_project_id'), table_name='music_cues')
    op.drop_index(op.f('ix_music_cues_active_audio_version_id'), table_name='music_cues')
    op.drop_table('music_cues')
    # ### end Alembic commands ###
