"""comments add type + parent

Revision ID: ab4d51906fc1
Revises: 8342ccd253d0
Create Date: 2026-02-17 21:43:42.334997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4d51906fc1'
down_revision: Union[str, Sequence[str], None] = '8342ccd253d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('comments', sa.Column('comment_type', sa.Text(), nullable=False))
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.drop_constraint(op.f('comments_media_version_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_segment_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'segments', ['segment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'media_versions', ['media_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_segment_id_fkey'), 'comments', 'segments', ['segment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('comments_media_version_id_fkey'), 'comments', 'media_versions', ['media_version_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_column('comments', 'comment_type')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
