"""media_versions partial unique indexes

Revision ID: ee7ae269db17
Revises: 82c668a047db
Create Date: 2026-02-18 21:17:04.294157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7ae269db17'
down_revision: Union[str, Sequence[str], None] = '82c668a047db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE media_versions DROP CONSTRAINT IF EXISTS uq_media_versions_version;")
    op.create_index('uq_media_versions_audio_cue_version', 'media_versions', ['cue_id', 'version_number'], unique=True, postgresql_where=sa.text("media_type = 'AUDIO' AND cue_id IS NOT NULL"))
    op.create_index('uq_media_versions_video_project_version', 'media_versions', ['project_id', 'version_number'], unique=True, postgresql_where=sa.text("media_type = 'VIDEO' AND segment_id IS NULL AND cue_id IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_media_versions_video_project_version', table_name='media_versions', postgresql_where=sa.text("media_type = 'VIDEO' AND segment_id IS NULL AND cue_id IS NULL"))
    op.drop_index('uq_media_versions_audio_cue_version', table_name='media_versions', postgresql_where=sa.text("media_type = 'AUDIO' AND cue_id IS NOT NULL"))
    op.create_unique_constraint(op.f('uq_media_versions_version'), 'media_versions', ['project_id', 'segment_id', 'media_type', 'version_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
